pkgs = [
  "libreoffice-fresh",
  "zathura",
  "zathura-cb",
  "zathura-djvu",
  "zathura-pdf-mupdf",
  "zathura-ps",
  "mpv",
  "imv",
  "yt-dlp",
  "ugrep",
  "lf",
  "ranger",
  "aria2",
  "plocate",
  "bubblejail",
  "helix",
  "gammastep",
  "flameshot-git",
  "kguiaddons5",
  "i3status-rust",
  "brightnessctl",
  "ungoogled-chromium-bin",
  "qbittorrent",
  "firefox",
  "torbrowser-launcher",
  "htop",
  "ncdu",
  "keepassxc",
  "wob",
]
