pkgs = [
  "base",
  "base-devel",
  "linux-zen",
  "linux-zen-headers",
  "linux-firmware",
  "man-db",
  "dbus-broker",
  "pkgfile",
  "rebuild-detector",
  "udisks2",
  "p7zip",
  "iwd",
  "polkit",
  "auto-cpufreq",
  "git",
  "thermald",
  "chrony",
  "reflector",
  "apparmor",
  "arch-audit",
  "zsh",
  "bash-completion",
  "neovim",
  "brightnessctl",
  "devtools",
  "downgrade",
  "keyd",
  "firewalld",
  "mosh",
  "pacman-contrib",
  "archlinux-contrib",
  "arch-install-scripts",
  "systemd-lock-handler",
  "age",
  "dex",
  "libnotify",
  "gvfs",
]
