[icons]
icons = "awesome6"

[[block]]
block = "net"
format = " $icon {$ssid |}$ip "
[[block.click]]
button = "left"
cmd = "$TERMINAL -a float_term nmtui"

[[block]]
block = "battery"
format = " $icon  $percentage "
full_format = " $icon  $percentage "
driver = "upower"
[[block.click]]
button = "left"
cmd = "auto-cpufreq-gtk"

[[block]]
block = "sound"
headphones_indicator = true
[[block.click]]
button = "left"
cmd = "qpwgraph"

[[block]]
block = "time"
format = " $icon $timestamp.datetime(f:'%a %Y-%m-%d %H:%M') "
