# ----------------------------------- #
#    Package Manager Configuration    #
# ----------------------------------- #

# Make sure to enter the exact command you use as the normal user!
# That means including 'sudo' or 'doas' or whatever if the command needs it.
# Where you would put packages, enter '#:?'.

# Example: install = "sudo apt install #:?"

install = "paru -S --noconfirm --needed #:?" # Example: sudo apt install #:?
remove = "paru -Rns #:?" # Example: sudo apt remove #:?
sync = "paru -Syy" # Example: sudo apt update
upgrade = "paru -Syyu" # Example: sudo apt upgrade

# ------------------------------- #
#    Additional configuration.    #
# ------------------------------- #

# many_pkg_args = BOOL: Can you supply many packages as an argument? Example: 'sudo apt install git vim wget'

config = { many_pkg_args = true }
